from tkinter import *
from tkinter import ttk
root = Tk()
root.title('Border Relief Types')
root.resizable(0, 0)
root.config(bg='#25D366')
def center_window(w, h):
    ws = root.winfo_screenwidth()
    hs = root.winfo_screenheight()
    x = (ws/2) - (w/2)
    y = (hs/2) - (h/2)
    root.geometry('%dx%d+%d+%d' % (w, h, x, y))
center_window(200, 260)
label01 = Label(root, text='Relief = Flat', bg='#E50914')
label01.config(borderwidth=5, relief='flat')
label02 = Label(root, text='Relief = Groove', bg='#E50914')
label02.config(borderwidth=10, relief='groove')
label03 = Label(root, text='Relief = Raised', bg='#E50914')
label03.config(borderwidth=10, relief='raised')
label04 = Label(root, text='Relief = Ridge', bg='#E50914')
label04.config(borderwidth=10, relief='ridge')
label05 = Label(root, text='Relief = Solid', bg='#E50914')
label05.config(borderwidth=5, relief='solid')
label06 = Label(root, text='Relief = Sunken', bg='#E50914')
label06.config(borderwidth=10, relief='sunken')
label01.grid(row=0, column=0, sticky=W, pady=2)
label02.grid(row=1, column=0, sticky=W, pady=2)
label03.grid(row=2, column=0, sticky=W, pady=2)
label04.grid(row=3, column=0, sticky=W, pady=2)
label05.grid(row=4, column=0, sticky=W, pady=2)
label06.grid(row=5, column=0, sticky=W, pady=2)
root.mainloop()
